import Config

# Configure your database
config :sandbox, Sandbox.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "pax_sandbox_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sandbox, SandboxWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "WDpQMeE+3r1o+u49ExaRirLoA7k6JCNVn4uQ0nrU597zl6jJl2gvTDT45kpj/fnO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sandbox, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sandbox, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Configure Phoenix.CodeReloader to reload pax as well as this application on every request, instead of just this app
config :sandbox, SandboxWeb.Endpoint, reloadable_apps: [:sandbox, :pax]

# Configure Phoenix.LiveReloader to Watch this app and the pax app during development and trigger reloads
config :phoenix_live_reload, :dirs, ["../", "./"]

# Watch static and templates for browser reloading.
config :sandbox, SandboxWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sandbox_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$",
      ~r"lib/pax/.*(interface|live|components).*(ex|heex)$"
    ]
  ]

# Configure Pax
config :pax, validate_config_spec: true

# Enable dev routes for dashboard and mailbox
config :sandbox, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  # debug_heex_annotations: true,
  # debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
